version: '3.7'
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: eventsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pololisjos88@#
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: